### ISSUE TITLE
运行 ./deploy.sh 报错。

### ISSUE THREAD

**Issue by KnowsCount** [Maicius/QQZoneSwipper#1]
- [x] 最新版 QQZoneSwiper
- [x] 安装最新 yarn
- [x] 试过 CentOS 7 服务器
- [x] 试过本地 macOS Mojave 10.14.6

---

报错信息（CentOS 与 macOS 相同）：
![image](https://raw.githubusercontent.com/KnowsCount/MarkdownPhotos/master/Res/Screenshot%202020-08-16%20at%2002.04.51.png)

望大佬解决！谢谢——

**Comment by Maicius** [comment]
不好意思，这个项目脚手架是别人搭的，我reademe还没来得及更新，不要用deploy.sh，不要用yarn，先试下直接在项目根目录下npm install --save，然后npm run start 启动

**Comment by KnowsCount** [comment]
OK 谢谢大佬
